### ISSUE TITLE
Bio_Industries updates to an old version

### ISSUE THREAD

**Issue by nihilistzsche** [raiguard/factorio_mod_manager#2]
Hey raiguard,

  I'm not entirely sure how you could solve this, but whenever I run fmm update it grabs Bio_Industries 2.7.0, which while appearing to be newer than Bio_Industries 1.1.0, is actually an older version that errors, it seems the author reset the version numbers at some point.  Perhaps an exception could be made to ignore this.

**Comment by raiguard** [comment]
Thanks for the report. I'll test this once I implement mod downloading/updating in the Go rewrite.
