### ISSUE TITLE
Why Go rewrite?

### ISSUE THREAD

**Issue by Kixunil** [raiguard/factorio_mod_manager#4]
Just curious, this was originally in Rust, why was it rewritten?

**Comment by raiguard** [comment]
I was spending more time fighting with the borrow checker than I was spending writing code. Go is significantly simpler, easier, and more enjoyable to write in.

**Comment by Kixunil** [comment]
I guess you were (are) a Rust newbie, right? Thanks for explaining!

**Comment by raiguard** [comment]
This was my second project with the language, and I had been writing it for eight months. I was able to write it, but I just didn't enjoy it.

**Comment by Kixunil** [comment]
Sure, thanks for writing the tool and good luck in your next project!
