### ISSUE TITLE
Which path do I set as `FACTORIO_PATH`? 

### ISSUE THREAD

**Issue by gamma-delta** [raiguard/factorio_mod_manager#7]
Hello,

I'm trying to write a little script to help me use fmm, on Linux (KDE neon).

Setting the factorio path to `~/.factorio` fails with `invalid game directory`. Looking at the source code, it looks like it's because it can't find `data/base/info.json`.

However, setting it to where Factorio is actually installed, in `~/.steam/steam/steamapps/common/Factorio`, it can't find the `mods` directory. I'm pretty sure the mods are supposed to be in the `~/.factorio` directory, though.

So what do I set as the path? It seems the manager needs both stuff need to be the same.

**Comment by gamma-delta** [comment]
Aha. What worked for me is, in `~/.steam/steam/steamapps/common/Factorio`, editing `config-path.ini` and setting `config-path` to `./config`.

**Comment by raiguard** [comment]
Yeah, at the moment fmm doesn't handle `config-path.ini` or `config.ini`. It's on the todo.
