### ISSUE TITLE
No compatible release found was found for 248k

### ISSUE THREAD

**Issue by matya** [raiguard/factorio_mod_manager#8]
I am trying to download mods for a little bit older save as a testrun for a mod-manager setup I am putting together.

One of my save game has following two mods which are somehow problematic:

```bash
jmatya@mini:~/factorio/factorio_1.1.101> ../fmm list ../../factorio-saves/248k_fmm_test.zip
248k 1.0.29                                 <<<
DiscoScience 1.1.3
FNEI 0.4.1
MaxRateCalculator 3.4.48
Squeak Through 1.8.2
base 1.1.101
even-distribution 1.0.10
exotic-industries-graphics-2 0.5.0          <<<
```

when I try to sync it, it shows me:
```bash
jmatya@mini:~/factorio/factorio_1.1.101> ../fmm sync ../../factorio-saves/248k_fmm_test.zip
disabled all mods
fetching info for 248k
no compatible release was found
fetching info for exotic-industries-graphics-2
no compatible release was found
enabled DiscoScience 1.1.3
enabled even-distribution 1.0.10
enabled FNEI 0.4.1
enabled MaxRateCalculator 3.4.48
enabled Squeak Through 1.8.2
jmatya@mini:~/factorio/factorio_1.1.101>
```

As far I have seen, the issue comes from [GetMatchingRelease](https://github.com/raiguard/fmm/blob/ab38f784a2d40a821b6f1d7f05a11e2d7608273a/lib/portal.go#L64) returning `ErrNoCompatibleRelease` because it did not find any compatible mod release (?), which seems strange to me, as the [mod api endpoint used](https://mods.factorio.com/api/mods/248k/full) should return the latest version available in general for the game version of 1.1.101 if I am not mistaken:
```json
{"download_url":"/download/248k/62bc750de793102bd6f77182","file_name":"248k_1.0.29.zip",
 "info_json":{"dependencies":["base >= 1.0.0","?Booktorio","?informatron","?Krastorio2","?IndustrialRevolution","?space-exploration","?RealisticReactors"],"factorio_version":"1.1"},
"released_at":"2022-06-29T15:51:41.707000Z","sha1":"32bd230a2d2a0f77c18075ff2f7094f4ddc2b7b1","version":"1.0.29"}
```

I can provide you a chunk-stripped version of the save game (8MB) if you want to reproduce it.

Also> Would it be possible to add some kind of debug-messages or verbose mode, that could be used in such case?

(PS> I'd also love a json-formatted output of the CLI for some additional plumbing-automation around it 😉)

**Comment by raiguard** [comment]
Thanks, sorry for the wait! I would appreciate if you could open separate issues with more specific details about your feature requests.
